package modulith

import (
	"fmt"
	"sort"
	"strings"
)

// Version is the gomodulith library version.
const Version = "0.5.0"

// ContractHeader is the heading used at the top of generated contracts. Tools
// can rely on it to detect a gomodulith-generated contract.
const ContractHeader = "Architecture Contract"

// ExportContract returns a Markdown architecture contract describing the
// modules, their public surfaces, dependency rules and published events,
// together with the current verification status.
//
// The contract is written to be read by humans and AI coding agents alike:
// it states, for every module, what other code may and may not do with it, so
// an agent can avoid introducing architecture violations before writing code.
func (a *Application) ExportContract() ([]byte, error) {
	if !a.loaded {
		return nil, fmt.Errorf("modulith: application not loaded")
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", ContractHeader)
	fmt.Fprintf(&b, "> Generated by gomodulith v%s. Do not edit by hand. Re-run `gomodulith contract` after architecture changes.\n\n", Version)

	fmt.Fprintf(&b, "This document is the authoritative description of the application's modular architecture. "+
		"AI coding agents SHOULD read it before modifying code and MUST NOT violate the rules below.\n\n")

	// Modules in deterministic order.
	mods := a.Modules()
	sort.SliceStable(mods, func(i, j int) bool { return mods[i].Name < mods[j].Name })

	graph := a.BuildGraph()

	fmt.Fprintf(&b, "## Modules (%d)\n\n", len(mods))
	for _, m := range mods {
		fmt.Fprintf(&b, "### %s\n\n", m.Name)
		if m.RootDir != "" {
			fmt.Fprintf(&b, "- Directory: `%s`\n", m.RootDir)
		}
		if len(m.PublicPackages) > 0 {
			fmt.Fprintf(&b, "- Public API packages:\n")
			for _, p := range m.PublicPackages {
				fmt.Fprintf(&b, "  - `%s`\n", p)
			}
		} else {
			fmt.Fprintf(&b, "- Public API packages: (none)\n")
		}
		eventPkgs := sortedKeys(m.eventPackageOf(a.config))
		if len(eventPkgs) > 0 {
			fmt.Fprintf(&b, "- Event packages:\n")
			for _, p := range eventPkgs {
				fmt.Fprintf(&b, "  - `%s`\n", p)
			}
		}
		if len(m.PublishedEvents) > 0 {
			fmt.Fprintf(&b, "- Publishes events: %s\n", strings.Join(m.PublishedEvents, ", "))
		}
		switch {
		case len(m.AllowedDependencies) > 0:
			fmt.Fprintf(&b, "- Allowed dependencies: %s\n", strings.Join(m.AllowedDependencies, ", "))
		case a.explicit:
			fmt.Fprintf(&b, "- Allowed dependencies: (closed — may not depend on any module)\n")
		default:
			fmt.Fprintf(&b, "- Allowed dependencies: (open — may depend on any module through its public surface)\n")
		}
		if len(m.ForbiddenDependencies) > 0 {
			fmt.Fprintf(&b, "- Forbidden dependencies: %s\n", strings.Join(m.ForbiddenDependencies, ", "))
		}
		if len(m.EventDrivenModules) > 0 {
			fmt.Fprintf(&b, "- Event-driven towards: %s (only their event packages may be imported)\n", strings.Join(m.EventDrivenModules, ", "))
		}
		depends := graph.DependenciesOf(m.Name)
		if len(depends) > 0 {
			var names []string
			for _, d := range depends {
				names = append(names, d.To.Name)
			}
			fmt.Fprintf(&b, "- Depends on: %s\n", strings.Join(names, ", "))
		} else {
			fmt.Fprintf(&b, "- Depends on: (none)\n")
		}
		fmt.Fprintf(&b, "\n")
	}

	fmt.Fprintf(&b, "## Rules\n\n")
	fmt.Fprintf(&b, "1. A module may import another module's **public API packages** (`<module>/%s/...`) and **event packages** (`<module>/%s/...`).\n", a.config.APIElement, a.config.EventElement)
	fmt.Fprintf(&b, "2. Imports into any other package of another module are **violations**.\n")
	fmt.Fprintf(&b, "3. A module must only depend on its allowed dependencies; forbidden dependencies are never allowed.\n")
	fmt.Fprintf(&b, "4. Event-driven modules may import the target module's event packages only.\n")
	fmt.Fprintf(&b, "5. Module dependencies must be acyclic.\n")
	fmt.Fprintf(&b, "6. Published event types must exist in the publishing module.\n\n")

	res, err := a.Verify()
	if err != nil {
		return nil, err
	}
	fmt.Fprintf(&b, "## Verification status\n\n")
	if res.OK {
		fmt.Fprintf(&b, "- **Status: OK** — the architecture conforms to these rules.\n")
	} else {
		fmt.Fprintf(&b, "- **Status: VIOLATIONS** — %d error(s), %d warning(s).\n",
			len(res.Errors()), len(res.Warnings()))
	}
	fmt.Fprintf(&b, "- Run `gomodulith verify` to re-check, and `gomodulith diff <base> <head>` to review architecture changes.\n")
	return []byte(b.String()), nil
}
