package modulith

import (
	"strings"
	"testing"
)

func TestExportContract(t *testing.T) {
	files := defaultFixture()
	files["internal/user/events/events.go"] = eventFile("events", []string{"UserRegistered"}, nil)
	files["internal/notifications/api/api.go"] = goFile("api", []string{fixtureModule + "/internal/user/events"})
	files["internal/notifications/domain/dom.go"] = goFile("domain", nil)
	writeFixture(t, files)

	app := New().
		Module("user", "./internal/user/...").
		Module("order", "./internal/order/...").
		Module("payment", "./internal/payment/...").
		Module("notifications", "./internal/notifications/...")
	app.ModuleRules("user").PublishEvents("UserRegistered")
	app.ModuleRules("order").AllowDependencies("user")
	app.ModuleRules("notifications").AllowDependencies("user").EventDrivenFrom("user")
	if err := LoadExplicit(ctx, app, "./..."); err != nil {
		t.Fatalf("LoadExplicit: %v", err)
	}

	doc, err := app.ExportContract()
	if err != nil {
		t.Fatalf("ExportContract: %v", err)
	}
	s := string(doc)

	for _, want := range []string{
		"# " + ContractHeader,
		"Generated by gomodulith v" + Version,
		"### user",
		"### order",
		"### notifications",
		"Publishes events: UserRegistered",
		"Allowed dependencies: user",
		"Event-driven towards: user",
		"## Rules",
		"## Verification status",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("contract missing %q:\n%s", want, s)
		}
	}
}

func TestExportContractJSONNoLoadError(t *testing.T) {
	app := New()
	if _, err := app.ExportContract(); err == nil {
		t.Fatal("expected error for unloaded application")
	}
}

func TestExportDOT(t *testing.T) {
	writeFixture(t, defaultFixture())
	app := mustLoad(t, "./...")

	dot := app.ExportDOT()
	for _, want := range []string{
		"digraph modules {",
		`"user" [label="user"];`,
		`"order" -> "user";`,
		`"payment" -> "order";`,
		"}",
	} {
		if !strings.Contains(dot, want) {
			t.Errorf("dot missing %q:\n%s", want, dot)
		}
	}
}

func TestScanDir(t *testing.T) {
	fixtureDir := writeFixture(t, defaultFixture())
	chdir(t, t.TempDir())

	app := ScanDir(t, fixtureDir, "./...")
	res, err := app.Verify()
	if err != nil {
		t.Fatalf("Verify: %v", err)
	}
	if !res.HasCode(CodeCrossModulePrivate) {
		t.Fatalf("expected cross-module violation from scanned dir:\n%s", Report(res))
	}
	if app.WorkingDir() != fixtureDir {
		t.Fatalf("WorkingDir = %q, want %q", app.WorkingDir(), fixtureDir)
	}
}

func TestScanDirWithConfig(t *testing.T) {
	fixtureDir := writeFixture(t, defaultFixture())
	chdir(t, t.TempDir())

	app := ScanDirWithConfig(t, fixtureDir, Config{ReportOrphans: true}, "./...")
	if app.Config().ReportOrphans != true {
		t.Fatal("config not applied")
	}
}

func TestConfigFileEventFields(t *testing.T) {
	data := []byte(`
modules:
  user:
    patterns: ["./internal/user/..."]
    publish_events: ["UserRegistered"]
  notifications:
    patterns: ["./internal/notifications/..."]
    event_driven_from: ["user"]
`)
	fc, err := ParseConfig(data, ConfigYAML)
	if err != nil {
		t.Fatalf("ParseConfig: %v", err)
	}
	user := fc.Modules["user"]
	if len(user.PublishEvents) != 1 || user.PublishEvents[0] != "UserRegistered" {
		t.Errorf("user publish_events = %v", user.PublishEvents)
	}
	notif := fc.Modules["notifications"]
	if len(notif.EventDrivenFrom) != 1 || notif.EventDrivenFrom[0] != "user" {
		t.Errorf("notifications event_driven_from = %v", notif.EventDrivenFrom)
	}
}

func TestConfigFileEventElement(t *testing.T) {
	fc, err := ParseConfig([]byte("event_element: evt\n"), ConfigYAML)
	if err != nil {
		t.Fatalf("ParseConfig: %v", err)
	}
	if fc.EventElement != "evt" {
		t.Errorf("EventElement = %q", fc.EventElement)
	}
	if got := fc.config().EventElement; got != "evt" {
		t.Errorf("config EventElement = %q", got)
	}
}
